#!/bin/bash
pathToFile=$(dirname $1)
fileName=$(basename $1)
fileName=${fileName%.*}
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

IFS=
result=$(./src/Compiler $1)

if [[ $result != "" ]]
then
	echo -e $result
	echo $result > $pathToFile/$fileName.ll
	llvm-as $pathToFile/$fileName.ll
	llvm-link -o $pathToFile/$fileName.bc $pathToFile/$fileName.bc $script_dir/lib/runtime.bc
fi