#!/bin/bash
pathToFile=$(dirname $1)
fileName=$(basename $1)
fileName=${fileName%.*}

result=$(./src/Compiler $1)

if [[ $result != "" ]]
then	
	echo $result > $pathToFile/$fileName.ll
	llvm-as $pathToFile/$fileName.ll
fi